### ISSUE TITLE
Check call target is not 0x0, and result true

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-bridges-sol#133]

**Comment by HackFisher** [comment]
https://mp.weixin.qq.com/s/qoizjz7SHrqmxVtCigr7DQ

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia-bridge-sol/blob/6e4efe70d93bfe5e264c3206fe83a13b007cb919/contracts/bridge/src/common/message/InboundLane.sol#L302
The target contract must be implement the interface `ICrossChainFilter` and return true, otherwise the filter call will be false

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia-bridge-sol/blob/6e4efe70d93bfe5e264c3206fe83a13b007cb919/contracts/bridge/src/common/message/InboundLane.sol#L295

The `dispatch_result` will be true at several situations:
1. none-code target address. (filter call could help)
2. call the right encoded call. (as we expected)
3. target contract have the `fallback()` function and call the wrong encoded call. (will cause trouble in app layer)
