### ISSUE TITLE
Support multi chain config in FeeMarket

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-bridges-sol#164]
Different bridged chain should have different config such as `collateralPerOrder`, `priceRatio` etc.

**Comment by wuminzhe** [comment]
what do you mean?

the market fee is getting from storage. so I think this can be implemented through multi storage keys. A storage key contains the the pallet name.

**Comment by hujw77** [comment]
One FeeMarket only serve for one bridge.
