### ISSUE TITLE
Replace old Token Issuing contract with new issuing contract(module)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-bridges-sol#28]

**Comment by HackFisher** [comment]
Closing this after Ethereum<>Darwinia bridge get upgraded, see https://github.com/darwinia-network/darwinia/issues/714

**Comment by xiaoch05** [comment]
new issuing contract address on ethereum 0xFBAD806Bdf9cEC2943be281FB355Da05068DE925
