### ISSUE TITLE
How to change all token logic contract in the same token type including deployed already ?

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-bridges-sol#86]
https://github.com/darwinia-network/darwinia-bridge-sol/blob/1a9b67755e7f44f97a1c0545b59454a1b5f25f78/contracts/mapping-token/contracts/darwinia/BasicMappingTokenFactory.sol#L59

**Comment by xiaoch05** [comment]
don't use logic contract anymore
